import { Association } from './types';

export const ASSOCIATIONS: Association[] = [
    { name: "Anoka Area Hockey Association", baseUrl: "https://www.anokaareahockey.com" },
    { name: "Apple Valley / Burnsville Hockey Association", baseUrl: "https://www.avbhockey.com" },
    { name: "Armstrong Cooper Youth Hockey Association", baseUrl: "https://www.armstrongcooperhockey.org" },
    { name: "Becker Big Lake Youth Hockey Association", baseUrl: "https://www.bblyha.com" },
    { name: "Blaine Youth Hockey Association", baseUrl: "https://www.byha.org" },
    { name: "Bloomington Jefferson Hockey", baseUrl: "https://www.jeffersonhockey.org" },
    { name: "Buffalo Hockey Association", baseUrl: "https://buffalo.pucksystems2.com" },
    { name: "Cambridge-Isanti Hockey Association", baseUrl: "https://www.cambridgeisantihockey.org" },
    { name: "Centennial Youth Hockey Association", baseUrl: "https://www.centennialhockey.org" },
    { name: "Champlin Park Youth Hockey Association", baseUrl: "https://www.cpyha.com" },
    { name: "Chaska Chanhassen Hockey Association", baseUrl: "https://www.cchockey.org" },
    { name: "Chisago Lakes Hockey Association", baseUrl: "https://www.chisagolakeshockey.org" },
    { name: "Coon Rapids Youth Hockey Association", baseUrl: "https://www.coonrapidshockey.com" },
    { name: "Cottage Grove Hockey Association", baseUrl: "https://www.cghockey.com" },
    { name: "Delano Area Youth Hockey Association", baseUrl: "https://www.datigers.com" },
    { name: "Eagan Hockey Association", baseUrl: "https://www.eaganhockey.com" },
    { name: "East Metro Stars Youth Hockey", baseUrl: "https://www.emshockey.org" },
    { name: "Eastview Hockey Association", baseUrl: "https://www.eastviewhockey.net" },
    { name: "Eden Prairie Hockey Association", baseUrl: "https://www.ephockey.com" },
    { name: "Edina Hockey Association", baseUrl: "https://www.edinahockeyassociation.com" },
    { name: "Elk River Youth Hockey Association", baseUrl: "https://www.elkriverhockey.org" },
    { name: "Forest Lake Hockey Association", baseUrl: "https://www.flhockey.org" },
    { name: "Hastings Hockey Association", baseUrl: "https://www.hastingshockey.com" },
    { name: "Hopkins Youth Hockey Association", baseUrl: "https://www.hopkinshockey.com" },
    { name: "Hutchinson Youth Hockey Association", baseUrl: "https://www.hutchhockey.org" },
    { name: "Inver Grove Heights Hockey Association", baseUrl: "https://www.ighha.org" },
    { name: "Lakeville Hockey Association", baseUrl: "https://www.lakevillehockey.org" },
    { name: "Mahtomedi Youth Hockey Association", baseUrl: "https://mahtomedihockey.pucksystems.com" },
    { name: "Mankato Area Hockey Association", baseUrl: "https://www.mankatohockey.com" },
    { name: "Minneapolis Youth Hockey Association", baseUrl: "https://www.mplshockey.com" },
    { name: "Minneapolis Titans Hockey", baseUrl: "https://www.minneapolistitanshockey.com" },
    { name: "Minnetonka Youth Hockey Association", baseUrl: "https://www.tonkahockey.org" },
    { name: "Mound Westonka Hockey Association", baseUrl: "https://www.westonkahockey.org" },
    { name: "Mounds View Irondale Youth Hockey Association", baseUrl: "https://www.mvihockey.org" },
    { name: "New Prague Youth Hockey Association", baseUrl: "https://www.newpraguehockey.com" },
    { name: "North Branch Area Hockey Association", baseUrl: "https://www.northbranchhockey.com" },
    { name: "Northfield Hockey Association", baseUrl: "https://www.northfieldhockey.net" },
    { name: "Osseo Maple Grove Hockey Association (OMGHA)", baseUrl: "https://www.omgha.com" },
    { name: "Owatonna Youth Hockey Association", baseUrl: "https://www.owatonnahockey.com" },
    { name: "Pine City Youth Hockey Association", baseUrl: "https://pinecityyouthhockey.pucksystems.com" },
    { name: "Prior Lake-Savage Hockey Association", baseUrl: "https://www.plsha.com" },
    { name: "Princeton Youth Hockey Association", baseUrl: "https://www.princetonyouthhockey.com" },
    { name: "Red Wing Amateur Hockey Association", baseUrl: "https://www.redwinghockey.org" },
    { name: "Rochester Youth Hockey Association", baseUrl: "https://www.ryha.net" },
    { name: "Rogers Youth Hockey Association", baseUrl: "https://www.rogershockey.com" },
    { name: "Rosemount Area Hockey Association", baseUrl: "https://www.rosemounthockey.org" },
    { name: "Roseville Area Hockey Association (RAYHA)", baseUrl: "https://www.rosevillehockey.org" },
    { name: "Sartell Youth Hockey Association", baseUrl: "https://www.sartellhockey.com" },
    { name: "Sauk Rapids Youth Hockey Association", baseUrl: "https://www.saukrapidshockey.org" },
    { name: "Shakopee Hockey Association", baseUrl: "https://www.shakopeehockey.com" },
    { name: "South St. Paul Youth Hockey Association", baseUrl: "https://sspyha.pucksystems2.com" },
    { name: "Spring Lake Park Youth Hockey Association", baseUrl: "https://slpyha.sportngin.com" },
    { name: "St. Cloud Youth Hockey Association", baseUrl: "https://www.stcloudhockey.com" },
    { name: "St. Francis Youth Hockey Association", baseUrl: "https://www.sfyha.org" },
    { name: "St. Louis Park Hockey Association", baseUrl: "https://www.slphockey.com" },
    { name: "St. Michael/Albertville (STMA) Youth Hockey", baseUrl: "https://www.stmayha.org" },
    { name: "St. Paul Capitals Hockey Association", baseUrl: "https://www.stpaulcapitalshockey.com" },
    { name: "Stillwater Area Hockey Association", baseUrl: "https://www.stillwaterhockey.net" },
    { name: "Waconia Hockey Association", baseUrl: "https://www.waconiahockey.org" },
    { name: "Wayzata Youth Hockey Association", baseUrl: "https://www.wayzatahockey.org" },
    { name: "West St. Paul Hockey Association (Sibley)", baseUrl: "https://www.warrioryouthhockey.org" },
    { name: "White Bear Lake Area Hockey Association", baseUrl: "https://www.wblhockey.com" },
    { name: "Woodbury Area Hockey Club", baseUrl: "https://www.woodburyhockey.com" }
];
